//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpiritualGiftsTest.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SpiritualGiftsTest.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        internal static string SpiritualGiftsTestTitle {
            get {
                return ResourceManager.GetString("SpiritualGiftsTestTitle", resourceCulture);
            }
        }
        
        internal static string BibleStudyTitle {
            get {
                return ResourceManager.GetString("BibleStudyTitle", resourceCulture);
            }
        }
        
        internal static string NavButtonBegin {
            get {
                return ResourceManager.GetString("NavButtonBegin", resourceCulture);
            }
        }
        
        internal static string NavButtonContinue {
            get {
                return ResourceManager.GetString("NavButtonContinue", resourceCulture);
            }
        }
        
        internal static string NavButtonFinish {
            get {
                return ResourceManager.GetString("NavButtonFinish", resourceCulture);
            }
        }
        
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        internal static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        internal static string Tongan {
            get {
                return ResourceManager.GetString("Tongan", resourceCulture);
            }
        }
        
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        internal static string Fijian {
            get {
                return ResourceManager.GetString("Fijian", resourceCulture);
            }
        }
        
        internal static string Acts412 {
            get {
                return ResourceManager.GetString("Acts412", resourceCulture);
            }
        }
        
        internal static string Acts412v {
            get {
                return ResourceManager.GetString("Acts412v", resourceCulture);
            }
        }
        
        internal static string EnglishCode {
            get {
                return ResourceManager.GetString("EnglishCode", resourceCulture);
            }
        }
        
        internal static string TonganCode {
            get {
                return ResourceManager.GetString("TonganCode", resourceCulture);
            }
        }
        
        internal static string SpanishCode {
            get {
                return ResourceManager.GetString("SpanishCode", resourceCulture);
            }
        }
        
        internal static string FijianCode {
            get {
                return ResourceManager.GetString("FijianCode", resourceCulture);
            }
        }
    }
}
